### ISSUE TITLE
compile error on nginx 1.9.7

### ISSUE THREAD

**Issue by iceking2nd** [qudreams/nginx-http-radius-module#2]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I src/nginx-http-radius-module/../libmyradclient/ -I objs -I src/http -I src/http/modules -I src/http/v2 -I src/mail -I src/stream \
                -o objs/addon/nginx-http-radius-module/ngx_http_auth_radius.o \
                src/nginx-http-radius-module/ngx_http_auth_radius.c
src/nginx-http-radius-module/ngx_http_auth_radius.c: In function ‘ngx_http_auth_radius_connect’:
src/nginx-http-radius-module/ngx_http_auth_radius.c:99: error: ‘ngx_event_t’ has no member named ‘lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:99: error: ‘ngx_connection_t’ has no member named ‘lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:100: error: ‘ngx_event_t’ has no member named ‘lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:100: error: ‘ngx_connection_t’ has no member named ‘lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:101: error: ‘ngx_event_t’ has no member named ‘own_lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:101: error: ‘ngx_connection_t’ has no member named ‘lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:102: error: ‘ngx_event_t’ has no member named ‘own_lock’
src/nginx-http-radius-module/ngx_http_auth_radius.c:102: error: ‘ngx_connection_t’ has no member named ‘lock’
make[1]: **\* [objs/addon/nginx-http-radius-module/ngx_http_auth_radius.o] Error 1
make[1]: Leaving directory `/var/tmp/nginx-1.9.7'
make: **\* [build] Error 2

**Comment by qudreams** [comment]
I have fixed it.please checkout new code and rebuild again.
